/*USE LABORATORIO;
ALTER TABLE EMPLEADOS ADD NOMBRE_EMPLEADO VARCHAR(30) AFTER IDEMPLEADO;
UPDATE EMPLEADOS
SET NOMBRE_EMPLEADO = CONCAT(APELLIDOS, ', ', NOMBRE);
ALTER TABLE EMPLEADOS DROP APELLIDOS, DROP NOMBRE;
SELECT * FROM EMPLEADOS;*/
/*ALTER TABLE CLIENTES ADD TIPO VARCHAR(3);
UPDATE CLIENTES
SET TIPO = 'VIP' WHERE CIUDAD = 'Madrid';
SELECT * FROM CLIENTES;*/
/*ALTER TABLE CLIENTES MODIFY TELEFONO VARCHAR(20);
UPDATE CLIENTES
SET TELEFONO = CONCAT('+34-', TELEFONO) WHERE TELEFONO IS NOT NULL;
SELECT * FROM CLIENTES;*/
/*ALTER TABLE PRODUCTOS ADD FECHA DATE;
UPDATE PRODUCTOS
SET FECHA = CONCAT(ANO,'-',MES,'-',DIA);
ALTER TABLE PRODUCTOS DROP ANO, DROP MES, DROP DIA;
SELECT * FROM PRODUCTOS;
UPDATE PRODUCTOS
SET ORIGEN = 'ESPAÑA' WHERE ORIGEN = 'ESPANA';*/

/*ALTER TABLE PRODUCTOS_NEPTUNO MODIFY SUSPENDIDO VARCHAR(2);
UPDATE PRODUCTOS_NEPTUNO
SET SUSPENDIDO = IF(SUSPENDIDO = 0, 'NO', 'SI');
SELECT * FROM PRODUCTOS_NEPTUNO;*/

/*UPDATE PRODUCTOS_NEPTUNO
SET PRECIOUNIDAD = ROUND(PRECIOUNIDAD*1.1, 2);
SELECT * FROM PRODUCTOS_NEPTUNO;*/

/*SELECT * FROM PROVEEDORES;
UPDATE PROVEEDORES
SET REGION = NULL WHERE REGION = '';*/

/*SELECT * FROM CLIENTES;
UPDATE CLIENTES
SET CIUDAD = CONCAT(UPPER(LEFT(CIUDAD,1)), LOWER(SUBSTRING(CIUDAD, 2, LENGTH(CIUDAD))));*/

/*CREATE TABLE PRODUCTOS_SUSPENDIDOS
SELECT * FROM PRODUCTOS_NEPTUNO WHERE SUSPENDIDO = 'SI';
SELECT * FROM PRODUCTOS_SUSPENDIDOS*/

/*SET SQL_SAFE_UPDATES = 0;
UPDATE PRODUCTOS_NEPTUNO
SET SUSPENDIDO = 'SI' WHERE IDPROVEEDOR = 1;
SELECT * FROM PRODUCTOS_NEPTUNO;*/

USE LABORATORIO;
SELECT * FROM PRODUCTOS_NEPTUNO;
SELECT * FROM PRODUCTOS_SUSPENDIDOS;
INSERT INTO PRODUCTOS_SUSPENDIDOS(IDPRODUCTO, NOMBREPRODUCTO, NOMBRECONTACTO, NOMBRECATEGORIA, PRECIOUNIDAD,
	SUSPENDIDO, IDPROVEEDOR)
    SELECT IDPRODUCTO, NOMBREPRODUCTO, NOMBRECONTACTO, NOMBRECATEGORIA, PRECIOUNIDAD, SUSPENDIDO,
    IDPROVEEDOR FROM PRODUCTOS_NEPTUNO WHERE SUSPENDIDO = 'SI';
SET SQL_SAFE_UPDATES = 0;
DELETE FROM PRODUCTOS_NEPTUNO WHERE SUSPENDIDO = 'SI';

USE BONUS_TRACK;
SET SQL_SAFE_UPDATES = 0;
UPDATE TOP_SPOTIFY
SET TITULO = UPPER(TITULO), ARTISTA = UPPER(ARTISTA);                         
SELECT * FROM TOP_SPOTIFY;
ALTER TABLE TOP_SPOTIFY ADD PERMANENCIA INT;
UPDATE TOP_SPOTIFY SET PERMANENCIA = YEAR(CURDATE()) - ANO;

CREATE TABLE ULTIMOS_LANZAMIENTOS
SELECT * FROM TOP_SPOTIFY WHERE PERMANENCIA <= 3;
DELETE FROM TOP_SPOTIFY WHERE PERMANENCIA <= 3;
SELECT * FROM ULTIMOS_LANZAMIENTOS;

INSERT INTO TOP_SPOTIFY VALUES (610, 'GOD CONTROL', 'MADONA', 'POP', 2018, 3);
INSERT INTO ULTIMOS_LANZAMIENTOS (ID, TITULO, ARTISTA, GENERO, ANO, PERMANENCIA)
SELECT ID, TITULO, ARTISTA, GENERO, ANO, PERMANENCIA FROM TOP_SPOTIFY WHERE PERMANENCIA <= 3;
DELETE FROM TOP_SPOTIFY WHERE PERMANENCIA <= 3;

use laboratorio;
/*ESTO NO FUNCIONA, PUES IDCLIENTE DE LA TABLA CLIENTES_NEPTUNO NO ES IGUAL AL IDCLIENTE DE LA TABLA FACTURAS
SELECT C.IDCLIENTE, SUM(MONTO) FROM CLIENTES_NEPTUNO C, FACTURAS F
	WHERE C.IDCLIENTE = F.IDCLIENTE GROUP BY C.IDCLIENTE;*/
    
SELECT * FROM PRODUCTOS_NEPTUNO
WHERE PRECIOUNIDAD > (SELECT AVG(PRECIOUNIDAD) FROM PRODUCTOS_NEPTUNO)
ORDER BY NOMBREPRODUCTO;
    
SELECT * FROM PRODUCTOS_NEPTUNO
WHERE PRECIOUNIDAD > (SELECT MAX(PRECIOUNIDAD) FROM PRODUCTOS_SUSPENDIDOS)
ORDER BY PRECIOUNIDAD DESC;

SELECT * FROM VARONES
WHERE SEMANAS < (SELECT MIN(SEMANAS) FROM INDETERMINADOS);

SELECT * FROM PRODUCTOS_NEPTUNO
WHERE LEFT(NOMBREPRODUCTO,1) = (SELECT LEFT(NOMBRE_EMPLEADO, 1) FROM EMPLEADOS WHERE IDEMPLEADO = 8)
ORDER BY NOMBREPRODUCTO;

SELECT * FROM PRODUCTOS_NEPTUNO
WHERE (SELECT MAX(IDPROVEEDOR) FROM PROVEEDORES)
ORDER BY NOMBREPRODUCTO;

SELECT * FROM PRODUCTOS_NEPTUNO
	WHERE NOMBRECATEGORIA = 'Bebidas'
	AND PRECIOUNIDAD > (SELECT MAX(PRECIOUNIDAD) FROM PRODUCTOS_NEPTUNO
		WHERE NOMBRECATEGORIA = 'Condimentos');
        
SELECT * FROM MUJERES
	WHERE EDAD_MADRE > (SELECT MAX(EDAD_MADRE) FROM VARONES);
    
SELECT NOMBRECOMPANIA, CIUDAD, PAIS FROM CLIENTES_NEPTUNO
	WHERE NOMBRECOMPANIA IN (SELECT NOMBRECOMPANIA FROM PEDIDOS_NEPTUNO
		WHERE CARGO > 500) ORDER BY NOMBRECOMPANIA;
        
SELECT IDCLIENTE, NOMBRECOMPANIA, CIUDAD, PAIS,
	CASE WHEN PAIS IN ('MÉXICO', 'CANADÁ', 'ESTADOS UNIDOS') THEN 'América del Norte'
		 WHEN PAIS IN ('ARGENTINA', 'BRASIL', 'VENEZUELA') THEN 'América del Sur'
		 ELSE 'Europa'
    END CONTINENTE
FROM CLIENTES_NEPTUNO ORDER BY CONTINENTE AND PAIS;

SELECT IDPEDIDO, NOMBRECOMPANIA, FECHAPEDIDO, CARGO,
	CASE WHEN CARGO > 700 THEN 'EXCELENTE'
		 WHEN CARGO > 500 THEN 'MUY BUENO'
         WHEN CARGO > 250 THEN 'BUENO'
         WHEN CARGO > 50 THEN 'REGULAR'
         ELSE 'MALO'
	END EVALUACION
    FROM PEDIDOS_NEPTUNO ORDER BY CARGO DESC;
    
SELECT IDPRODUCTO, NOMBREPRODUCTO, NOMBRECATEGORIA, PRECIOUNIDAD,
	CASE WHEN PRECIOUNIDAD > 100 THEN 'DELUXE'
		 WHEN PRECIOUNIDAD > 10 THEN 'REGULAR'
         ELSE 'ECONOMICO'
	END TIPO
FROM PRODUCTOS_NEPTUNO ORDER BY PRECIOUNIDAD DESC;

USE LABORATORIO;
SELECT * FROM VARONES WHERE FECHA LIKE '%/09/%'
AND SEMANAS > 40 AND NACIONALIDAD = 'Chilena' AND ESTADO_CIVIL_MADRE = 'Casada'
UNION
SELECT * FROM MUJERES WHERE FECHA LIKE '%/09/%'
AND SEMANAS > 40 AND NACIONALIDAD = 'Chilena' AND ESTADO_CIVIL_MADRE = 'Casada'
UNION
SELECT * FROM INDETERMINADOS WHERE FECHA LIKE '%/09/%'
AND SEMANAS > 40 AND NACIONALIDAD = 'Chilena' AND ESTADO_CIVIL_MADRE = 'Casada';

SELECT *, 'A LA VENTA' AS CONDICION FROM PRODUCTOS_NEPTUNO WHERE PRECIOUNIDAD > 80
UNION
SELECT *, 'SUSPENDIDO' AS CONDICION FROM PRODUCTOS_SUSPENDIDOS WHERE PRECIOUNIDAD > 80  ORDER BY NOMBREPRODUCTO;

SELECT * FROM PRODUCTOS_NEPTUNO WHERE NOMBRECATEGORIA = 'BEBIDAS'
UNION ALL
SELECT * FROM PRODUCTOS_SUSPENDIDOS WHERE NOMBRECATEGORIA = 'BEBIDAS' ORDER BY NOMBREPRODUCTO;

INSERT INTO PRODUCTOS_SUSPENDIDOS(IdProducto, NombreProducto, NombreContacto, NombreCategoria, PrecioUnidad, SUSPENDIDO, IdProveedor)
SELECT IdProducto, NombreProducto, NombreContacto, NombreCategoria, PrecioUnidad, SUSPENDIDO, IdProveedor FROM PRODUCTOS_NEPTUNO WHERE IDPRODUCTO = '43';

SET SQL_SAFE_UPDATES = 0;
DELETE FROM PRODUCTOS_SUSPENDIDOS WHERE IDPRODUCTO = 43;

SELECT * FROM PRODUCTOS_SUSPENDIDOS ORDER BY IDPRODUCTO;

USE LABORATORIO;
CREATE TABLE EQUIPOS (EQUIPO VARCHAR(20) PRIMARY KEY);
INSERT INTO EQUIPOS
VALUES ('ARGENTINA'), ('BRASIL'), ('PARAGUAY'), ('CHILE'), ('URUGUAY'), ('COLOMBIA'), ('ECUADOR'), ('PERU'), ('BOLIVIA'), ('VENEZUELA');
SELECT * FROM EQUIPOS;

SELECT * FROM EQUIPOS L CROSS JOIN EQUIPOS V WHERE L.EQUIPO <> V.EQUIPO ORDER BY L.EQUIPO;

SELECT IDPRODUCTO, NOMBREPRODUCTO, NOMBRE_EMPLEADO FROM PRODUCTOS_NEPTUNO CROSS JOIN EMPLEADOS WHERE IDPRODUCTO = IDEMPLEADO;

SELECT P.NOMBRECONTACTO, IDPRODUCTO, NOMBREPRODUCTO, PRECIOUNIDAD FROM PROVEEDORES P
JOIN PRODUCTOS_NEPTUNO PN ON P.IDPROVEEDOR = PN.IDPROVEEDOR ORDER BY P.NOMBRECONTACTO, NOMBREPRODUCTO;

SELECT P.NOMBRECONTACTO, IDPRODUCTO, NOMBREPRODUCTO, PRECIOUNIDAD FROM PROVEEDORES P, 
PRODUCTOS_NEPTUNO PN WHERE P.IDPROVEEDOR = PN.IDPROVEEDOR ORDER BY P.NOMBRECONTACTO, NOMBREPRODUCTO;

SELECT EMPRESA, NUMERO_PEDIDO, FECHA_PEDIDO, FORMA_PAGO FROM CLIENTES
JOIN PEDIDOS ON COD_CLIENTE = CODIGO_CLIENTE ORDER BY EMPRESA;

SELECT EMPRESA, NUMERO_PEDIDO, FECHA_PEDIDO, FORMA_PAGO FROM CLIENTES C
LEFT JOIN PEDIDOS P ON C.COD_CLIENTE = P.CODIGO_CLIENTE WHERE NUMERO_PEDIDO IS NULL ORDER BY EMPRESA;

SELECT EMPRESA FROM CLIENTES C
LEFT JOIN PEDIDOS P ON C.COD_CLIENTE = P.CODIGO_CLIENTE WHERE NUMERO_PEDIDO IS NULL ORDER BY EMPRESA;

SELECT * FROM PROVEEDORES P LEFT JOIN PRODUCTOS_NEPTUNO PN ON P.IDPROVEEDOR = PN.IDPROVEEDOR WHERE PN.IDPRODUCTO IS NULL;

SELECT * FROM PROVEEDORES P RIGHT JOIN PRODUCTOS_NEPTUNO PN ON P.IDPROVEEDOR = PN.IDPROVEEDOR WHERE PN.IDPROVEEDOR IS NULL;

USE BONUS_TRACK;

SELECT ARTISTA, TITULO FROM ULTIMOS_LANZAMIENTOS WHERE ANO = (SELECT MAX(ANO) FROM ULTIMOS_LANZAMIENTOS) ORDER BY ARTISTA, TITULO;

SELECT TITULO FROM TOP_SPOTIFY WHERE ARTISTA = 'LADY GAGA' AND PERMANENCIA = (SELECT MAX(PERMANENCIA) FROM TOP_SPOTIFY) ORDER BY TITULO;

SELECT ARTISTA, TITULO, CASE
WHEN GENERO LIKE '%POP%' THEN 'POP'
WHEN GENERO LIKE '%ELECTRO%' OR GENERO LIKE '%HOUSE%' THEN 'ELECTRÓNICA'
ELSE 'OTRO'
END AS TIPO
FROM TOP_SPOTIFY ORDER BY ARTISTA, TITULO;

SELECT * FROM TOP_SPOTIFY WHERE TITULO LIKE '%BREAK%'
UNION
SELECT * FROM ULTIMOS_LANZAMIENTOS WHERE TITULO LIKE '%BREAK%' ORDER BY TITULO;

SELECT *, 'ANTERIOR' ESTADO FROM TOP_SPOTIFY WHERE TITULO LIKE '%BREAK%'
UNION
SELECT *, 'ULTIMO' ESTADO FROM ULTIMOS_LANZAMIENTOS WHERE TITULO LIKE '%BREAK%' ORDER BY TITULO;

USE LIBRERIA;

SELECT * FROM LIBROS WHERE PRECIO > (SELECT AVG(PRECIO) FROM LIBROS) ORDER BY TITULO;

SELECT * FROM LIBROS WHERE CATEGORIA = 'NOVELAS' AND PRECIO > (SELECT MAX(PRECIO) FROM LIBROS WHERE CATEGORIA = 'ENSAYOS') ORDER BY PRECIO DESC;

/*DESAFIO PUNTO 3. EL RESULTADO ORIENTA HACIA UN CAMPO 'PERMANENCIA' QUE NO EXISTE*/

SELECT * FROM EMPLEADOS WHERE PUESTO_ID = (SELECT MAX(PUESTO_ID) FROM EMPLEADOS);

SELECT LIBRO_ID, TITULO, CATEGORIA, PRECIO, CASE
WHEN PRECIO < 15 THEN 'ECONÓMICO'
WHEN PRECIO BETWEEN 15 AND 30 THEN 'REGULAR'
ELSE 'DELUXE'
END AS TIPO
FROM LIBROS WHERE PRECIO IS NOT NULL ORDER BY TITULO;

/*EN LA PROXIMA CONSULTA, NO EXISTE LA TABLA EMPLEADOS_ANTERIORES*/
SELECT CONCAT(APELLIDO,', ', NOMBRE) FROM EMPLEADOS WHERE PUESTO_ID = '9'
UNION
SELECT CONCAT(APELLIDO,', ', NOMBRE) FROM EMPLEADOS_ANTERIORES WHERE PUESTO_ID ='9' ORDER BY EMPLEADO;

SELECT L.LIBRO_ID, TITULO, PRECIO, LOCAL_ID, FACTURA_NRO, CANTIDAD, ROUND(PRECIO*CANTIDAD,2) AS TOTAL
FROM LIBROS L ,VENTAS V WHERE L.LIBRO_ID = V.LIBRO_ID ORDER BY TITULO;

SELECT L.TITULO FROM LIBROS L LEFT JOIN VENTAS V ON L.LIBRO_ID = V.LIBRO_ID WHERE V.FACTURA_NRO IS NULL;

SELECT TITULO L FROM LIBROS WHERE L='EL CASTIGO DE DIOS';